// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ePizzaHub.Core.Entities
{
    public partial class PaymentDetail
    {
        [Key]
        public string Id { get; set; }
        [Required]
        public string TransactionId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Tax { get; set; }
        [Required]
        public string Currency { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Total { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Status { get; set; }
        public Guid CartId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal GrandTotal { get; set; }
        public DateTime CreatedDate { get; set; }
        public int UserId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("PaymentDetails")]
        public virtual User User { get; set; }
    }
}