// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ePizzaHub.Core.Entities
{
    public partial class User
    {
        public User()
        {
            Orders = new HashSet<Order>();
            PaymentDetails = new HashSet<PaymentDetail>();
            Roles = new HashSet<Role>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public bool EmailConfirmed { get; set; }
        public DateTime CreatedDate { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Order> Orders { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Users")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}